# -*- coding: utf-8 -*-
# @Time    : 2024/1/4 18:50
# @Author  : 黄朝阳
# @FileName: 基础路径配置        testing  production
# @Software: PyCharm

-
  environment: "production"

# 正式环境IP配置
  production_url:
    url: "https://yolink.quanyou.com.cn"

# 测试环境IP配置
  testing_url:
    url: "https://yolinkcs.quanyou.com.cn"