desiredCaps:
  #设备信息
  platformName: Android
  #设备系统版本
  paltformVersion: '13'
  #app包名
  appPackage: cn.com.quanyou.attnd
  #app启动activity
  appActivity: cn.com.quanyou.attnd.ui.SplashActivity
  #设备名字
  deviceName: 21091116AC
  #不清除应用数据
  noReset: False
  #允许输入中文
  unicodeKeyboard: True
  resetKeyboard: True
  #允许app获取相关权限
  autoGrantPermissions: True
  automationName: UiAutomator2
  #修改超时时长，默认60s
  newCommandTimeout: 3600